package com.halas.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CopterSOAPService", targetNamespace = "http://soap.service.halas.com/", wsdlLocation = "http://localhost:8080/YuriiHalasServer/copterSOAP?wsdl")
public class CopterSOAPService
        extends Service {

    private final static URL COPTERSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COPTERSOAPSERVICE_EXCEPTION;
    private final static QName COPTERSOAPSERVICE_QNAME = new QName("http://soap.service.halas.com/", "CopterSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/YuriiHalasServer/copterSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COPTERSOAPSERVICE_WSDL_LOCATION = url;
        COPTERSOAPSERVICE_EXCEPTION = e;
    }

    public CopterSOAPService() {
        super(__getWsdlLocation(), COPTERSOAPSERVICE_QNAME);
    }

    public CopterSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COPTERSOAPSERVICE_QNAME, features);
    }

    public CopterSOAPService(URL wsdlLocation) {
        super(wsdlLocation, COPTERSOAPSERVICE_QNAME);
    }

    public CopterSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COPTERSOAPSERVICE_QNAME, features);
    }

    public CopterSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CopterSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (COPTERSOAPSERVICE_EXCEPTION != null) {
            throw COPTERSOAPSERVICE_EXCEPTION;
        }
        return COPTERSOAPSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CopterServiceSOAP
     */
    @WebEndpoint(name = "CopterSOAPPort")
    public CopterServiceSOAP getCopterSOAPPort() {
        return super.getPort(new QName("http://soap.service.halas.com/", "CopterSOAPPort"), CopterServiceSOAP.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CopterServiceSOAP
     */
    @WebEndpoint(name = "CopterSOAPPort")
    public CopterServiceSOAP getCopterSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.halas.com/", "CopterSOAPPort"), CopterServiceSOAP.class, features);
    }

}
