
package com.halas.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CopterServiceSOAP", targetNamespace = "http://soap.service.halas.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CopterServiceSOAP {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoSuchCopterIdException_Exception
     * @throws MaximumDistanceExceededException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean goByDegree(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1)
        throws MaximumDistanceExceededException_Exception, NoSuchCopterIdException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoSuchCopterIdException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean deleteCopterById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws NoSuchCopterIdException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoSuchCopterIdException_Exception
     * @throws MaximumDistanceExceededException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean goUp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws MaximumDistanceExceededException_Exception, NoSuchCopterIdException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.halas.service.soap.CopterArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public CopterArray showAllCopters();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoSuchCopterIdException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean holdPosition(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws NoSuchCopterIdException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws DuplicateCopterIdException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addCopter(
        @WebParam(name = "arg0", partName = "arg0")
        Copter arg0)
        throws DuplicateCopterIdException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoSuchCopterIdException_Exception
     * @throws MaximumDistanceExceededException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean goDown(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws MaximumDistanceExceededException_Exception, NoSuchCopterIdException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws NoSuchCopterIdException_Exception
     * @throws MaximumDistanceExceededException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean moveToPositionById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Position arg1)
        throws MaximumDistanceExceededException_Exception, NoSuchCopterIdException_Exception
    ;

}
