
package com.halas.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DuplicateCopterIdException", targetNamespace = "http://soap.service.halas.com/")
public class DuplicateCopterIdException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DuplicateCopterIdException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DuplicateCopterIdException_Exception(String message, DuplicateCopterIdException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DuplicateCopterIdException_Exception(String message, DuplicateCopterIdException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.halas.service.soap.DuplicateCopterIdException
     */
    public DuplicateCopterIdException getFaultInfo() {
        return faultInfo;
    }

}
